In [5]:
import pandas as pd
import numpy as np
import scipy
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
%matplotlib inline
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_csv('Womens Clothing E-Commerce Reviews.csv')

In [3]:
df.dropna(axis=0,inplace=True)
df.drop(['Unnamed: 0'],1,inplace=True)
df=pd.get_dummies(df,columns=['Division Name','Department Name'])

In [6]:
Y = df['Class Name']
X = df.drop(['Class Name','Review Text','Title'],1)
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

In [7]:
from sklearn.cluster import KMeans

km=KMeans(n_clusters=len(df['Class Name'].unique()), random_state=42)

# Calculate predicted values.
y_pred =km.fit_predict(X_train)
y_pred=pd.Series(y_pred)

In [8]:
from sklearn import metrics
from sklearn.metrics import pairwise_distances   
print('Adjusted Rand Score:',metrics.adjusted_rand_score(y_pred,Y_train))
print('Homogenity Score:',metrics.homogeneity_score(y_pred,Y_train))
print('Completeness Score:',metrics.completeness_score(y_pred,Y_train))

kmean=pd.crosstab(y_pred,Y_train,rownames=['Clusters'])
accuracy=(sum(np.diagonal(kmean))/(kmean.sum().sum()))*100
print('K-means Accuracy for Class Name:',accuracy)
print('Comparing k-means clusters against the data:')
kmean

Adjusted Rand Score: 0.6071947151625389
Homogenity Score: 0.7203536889666031
Completeness Score: 0.8355894595552741
K-means Accuracy for Class Name: 3.6985119689454384
Comparing k-means clusters against the data:

Class Name,Blouses,Casual bottoms,Dresses,Fine gauge,Intimates,Jackets,Jeans,Knits,Layering,Legwear,Lounge,Outerwear,Pants,Shorts,Skirts,Sleep,Sweaters,Swim,Trend
Clusters,,,,,,,,,,,,,,,,,,,
0,107,0,188,41,7,30,31,175,2,6,21,13,32,7,31,5,44,18,4
1,184,1,385,60,7,56,57,290,7,7,40,16,77,22,59,12,91,14,8
2,21,0,32,5,1,6,3,17,1,2,4,0,3,2,4,2,9,4,0
3,25,0,44,4,1,3,6,26,1,0,5,1,4,0,3,3,9,3,0
4,84,0,156,40,4,23,25,123,3,9,11,7,30,4,24,7,35,7,7
5,93,0,181,34,3,23,36,148,3,2,28,9,43,7,20,4,40,7,12
6,11,0,29,2,0,3,1,28,0,0,2,1,4,2,4,1,9,0,1
7,15,0,40,2,2,5,7,22,0,0,4,1,13,0,8,1,4,2,0
8,12,0,42,4,0,1,5,26,1,1,6,1,8,1,5,0,3,1,1
9,6,0,14,7,0,1,3,11,0,0,1,1,3,1,7,0,6,0,0
10,68,0,123,18,5,19,19,100,3,1,17,11,30,3,14,4,38,9,0
11,148,0,341,40,5,36,69,248,4,5,40,14,68,16,50,9,74,10,6
12,95,0,215,28,2,25,36,167,5,1,18,9,55,12,31,10,49,8,5
13,7,0,21,2,0,5,2,14,0,1,3,1,5,2,4,0,5,2,0
14,65,0,126,20,2,11,20,82,3,2,13,3,18,8,12,5,16,5,2
15,144,0,342,38,6,33,56,225,9,5,22,6,65,6,37,11,78,13,4
16,66,0,139,38,5,10,25,95,1,4,16,7,26,11,24,5,31,6,3
17,6,0,22,6,0,2,3,20,0,0,5,0,3,0,1,0,3,0,0
18,57,0,143,36,4,17,35,109,2,2,11,4,30,3,15,5,27,1,6
19,9,0,18,0,0,0,1,11,1,1,0,2,5,1,1,1,3,0,3